### ISSUE TITLE
Feature request : FromJSON changes ?

### ISSUE THREAD

**Issue by stephanewierzbicki** [delphiframeworks/x-superobject#99]
Hello,

I don't know if this is possible but there is memory leaks when doing things like that :

```
Test := TTest.create;  <---- First instance
Test := TTest.FromJson(someJSONString); <---- 2nd instance
Test.free; <---- only second instance is freed
```

In this example TTest is instantiated twice. Is it possible to use the already existing Test instance instead of creating a new one ?

**Comment by vkrapotkin** [comment]
Uou can see how to do it exactly in FromJSON code
But what 's the reason you create this object twice?

**Comment by stephanewierzbicki** [comment]
Well, I'm using such code, and I found it cumbersome :

```
function TMyObject.SelfUpdate(
  const JSON: String): boolean;
var
  tmp: TMyObject;
begin
  inherited;
  try
    tmp := TMyObject.FromJSON(JSON);
    try
      self.Assign(tmp);
      result := true;
    finally
      tmp.Free;
    end;
  except
    result := false;
  end;
end;
```

Maybe this would be a better solution :

` tmp.AssignFromJSON(JSONSTRING);`

**Comment by vkrapotkin** [comment]
Let's make an experiment
```
TMyObject=class
  s:string;
  i:integer;
end;
...

  obj1:=TMyObject.Create();
  obj1.s:='Object1';
  obj1.i:=10;
  obj2:=TMyObject.Create();
  obj2.s:='Object2';
  obj2.i:=20;

  s:=obj1.AsJSON;
  obj2.FromJSON(s);
  ShowMessage(obj2.s);

```
obj2.FromJSON  working good for me in Delphi Berlin.
More correct way is to aviod using the constructor FromJSON - it's ideologically wrong)), but we can use
`  TSerializeParse.WriteObject(obj2,TSuperObject.Create(s));
`
in fact, they are the same

**Comment by stephanewierzbicki** [comment]
That's nice but I still have an issue. As soon as my object is going complex, list fields are empty...
For example, this exemple will not be updated

```
TMyObject = class(TPErsistent)
MyList : TObjectList<TOtherObject>
MyFooObject: TMyFooObject
end;
```
Lists and objects fields will remains empty
`TSerializeParse.WriteObject(MyObject ,TSuperObject.Create(s));`

**Comment by stephanewierzbicki** [comment]
Hello vkrapotkin,

 I'm using TSerializeParse and this is well working, :)
